id = "pink-cat-boo-theme"
name = "Pink Cat Boo"
version = "1.3.0"
schema_version = 1
authors = ["jjsalinas"]
description = "A port of the Pink Cat Boo VS Code theme by Fiona Fan (ftsamoyed) for Zed."
repository = "https://github.com/jjsalinas/PinkCatBooZed"

